#! usr/bin/env python


#imports
import rospy
from nav_msgs.msg import Odometry, OccupancyGrid

#global variables
isExplored = []

#functions
def exploredInit(msg):
    #intialize based on /map data
    isexplored = msg.data

def updateExplored(msg):
    #update isExplored based on tbot odometry data and dimensions


if __name__ == "__main__":
    #initialize node
    sub = rospy.Subscirber('map',OccupancyGrid, exploredInit)

    while(1):
        
